name: Install FlexPRET and dependencies (Linux only)
description: Install FlexPRET and dependencies (Linux only)
runs:
  using: "composite"
  steps:
    - name: Setup
      run: |
        # Clone the FlexPRET repository
        git clone --recurse-submodules https://github.com/pretis/flexpret

        # This rest is copied directly from FlexPRET's `azure-pipelines.yml`

        # Ubuntu 20.04 only has Verilator 4.028 but we neeed a more modern version
        # so we do not use 'sudo apt-get install -y -qq verilator' here.
        wget -q https://github.com/sifive/verilator/releases/download/4.036-0sifive2/verilator_4.036-0sifive2_amd64.deb -O verilator.deb
        sudo dpkg -i verilator.deb

        # Install riscv compiler
        wget -q https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/download/v8.3.0-2.3/xpack-riscv-none-embed-gcc-8.3.0-2.3-linux-x64.tar.gz -O riscv.tgz
        tar zxf riscv.tgz
        mv xpack-riscv-none-embed-gcc-8.3.0-2.3 ~/riscv-embed-gcc
        ln -s ~/riscv-embed-gcc/bin/riscv-none-embed-as ~/riscv-embed-gcc/bin/riscv32-unknown-elf-as
        ln -s ~/riscv-embed-gcc/bin/riscv-none-embed-ar ~/riscv-embed-gcc/bin/riscv32-unknown-elf-ar
        ln -s ~/riscv-embed-gcc/bin/riscv-none-embed-gcc ~/riscv-embed-gcc/bin/riscv32-unknown-elf-gcc
        ln -s ~/riscv-embed-gcc/bin/riscv-none-embed-ld ~/riscv-embed-gcc/bin/riscv32-unknown-elf-ld
        ln -s ~/riscv-embed-gcc/bin/riscv-none-embed-objdump ~/riscv-embed-gcc/bin/riscv32-unknown-elf-objdump
        ln -s ~/riscv-embed-gcc/bin/riscv-none-embed-objcopy ~/riscv-embed-gcc/bin/riscv32-unknown-elf-objcopy

        # Update submodules
        git submodule update --init --recursive
      shell: bash
    - name: Build FlexPRET and install to SDK
      run: |
        # Step into cloned directory
        cd flexpret

        # Source environment
        source bash.env

        # Build FlexPRET's high memory configuration and install it to SDK
        cd $FP_PATH && cmake -DFP_CONFIG=highmem -B build && cd build && make all install
      shell: bash
