name: Push RTI to Docker Hub
description: Build and push the RTI image to Docker Hub
inputs:
  tag:
    description: 'The tag of the RTI image to build and push'
    required: true
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Check out lingua-franca repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: src/lib/c/reactor-c/core/federated/RTI/rti.Dockerfile
        context: src/lib/c/reactor-c/
        push: true
        tags: depetrol/rti:${{ inputs.tag }}

