name: Prepare build environment (Linux only)
description: Set up Java, Maven, Gradle, etc.
inputs:
  lf-dir:
    description: 'Relative path to lingua-franca checkout (ending with a slash)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Java 17
      run: |
        echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
        echo "org.gradle.java.home=${JAVA_HOME_17_X64//\\/\/}" >> gradle.properties
        echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
      shell: bash
    - name: Check settings
      run: |
        echo $(which java)
        cat gradle.properties
        echo $JAVA_HOME
        echo "gradle-hash=$(cat ${{ github.workspace }}/${{ inputs.lf-dir }}gradle/wrapper/gradle-wrapper.properties | grep "distributionSha256Sum" | cut -d'=' -f2)" >> $GITHUB_ENV
      shell: bash
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: Gradle-${{ runner.os }}-${{ env.gradle-hash }}
