name: TypeScript-based tests

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - 'nightly'
    paths:
    - 'org.lflang/src/org/lflang/generator/ts/**'
    - 'org.lflang/src/lib/ts/**'

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

jobs:
  # Cancel previous workflow runs.
  cancel:
    uses: lf-lang/lingua-franca/.github/workflows/cancel.yml@master

# Check that automatic code formatting works.
# TODO: Uncomment after fed-gen is merged.
# format:
#   uses: lf-lang/lingua-franca/.github/workflows/format.yml@master
#   needs: cancel

  # Run the TypeScript integration tests.
  ts-tests:
    uses: lf-lang/lingua-franca/.github/workflows/ts-tests.yml@master
    needs: cancel

  # Run the serialization tests
  serialization-tests:
    uses: lf-lang/lingua-franca/.github/workflows/serialization-tests.yml@master
    needs: cancel
