# Main workflow for testing the Lingua Franca compiler.
name: Cpp

on:
  workflow_dispatch: # Allow the workflow to be triggered manually.
  # Trigger this workflow on push events, but only on master.
  push:
    branches:
      - master
  # Trigger this workflow also on pull_request events, but ignore the 'nightly' branch.
  pull_request:
    branches-ignore:
      - 'nightly'
    paths:
    - 'org.lflang/src/org/lflang/generator/cpp/**'
    - 'org.lflang/src/lib/cpp/**'

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

jobs:
  # Cancel previous workflow runs.
  cancel:
    uses: lf-lang/lingua-franca/.github/workflows/cancel.yml@master

# Check that automatic code formatting works.
# TODO: Uncomment after fed-gen is merged.
# format:
#   uses: lf-lang/lingua-franca/.github/workflows/format.yml@master
#   needs: cancel

  # Run the C++ benchmark tests.
  cpp-benchmark-tests:
    uses: lf-lang/benchmarks-lingua-franca/.github/workflows/benchmark-tests.yml@main
    with:
      target: 'Cpp'
    needs: cancel

  # Run the C++ integration tests.
  cpp-tests:
    uses: lf-lang/lingua-franca/.github/workflows/cpp-tests.yml@master
    needs: cancel

  # Run the C++ integration tests on ROS2.
  cpp-ros2-tests:
    uses: lf-lang/lingua-franca/.github/workflows/cpp-ros2-tests.yml@master
    needs: cancel

  # Run the serialization tests
  serialization-tests:
    uses: lf-lang/lingua-franca/.github/workflows/serialization-tests.yml@master
    needs: cancel
