# Main workflow for testing the Lingua Franca compiler.
name: CI

on:
  # Trigger this workflow on push events, but only on master.
  push:
    branches:
      - master
  # Trigger this workflow also on pull_request events, but ignore the 'nightly' branch.
  pull_request:
    branches-ignore:
      - 'nightly'
    paths-ignore:
    - 'org.lflang/src/org/lflang/generator/c/**'
    - 'org.lflang/src/org/lflang/generator/cpp/**'
    - 'org.lflang/src/org/lflang/generator/python/**'
    - 'org.lflang/src/org/lflang/generator/ts/**'
    - 'org.lflang/src/lib/c/**'
    - 'org.lflang/src/lib/platform/**'
    - 'org.lflang/src/lib/cpp/**'
    - 'org.lflang/src/lib/py/**'
    - 'org.lflang/src/lib/ts/**'

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

jobs:
  # Cancel previous workflow runs.
  cancel:
    uses: lf-lang/lingua-franca/.github/workflows/cancel.yml@master

# Check that automatic code formatting works.
# TODO: Uncomment after fed-gen is merged.
# format:
#   uses: lf-lang/lingua-franca/.github/workflows/format.yml@master
#   needs: cancel

  # Run the Rust integration tests.
  rs-tests:
    uses: lf-lang/lingua-franca/.github/workflows/rs-tests.yml@master
    needs: cancel

  # Run the Rust benchmark tests.
  rs-benchmark-tests:
    uses: lf-lang/benchmarks-lingua-franca/.github/workflows/benchmark-tests.yml@main
    with:
      target: 'Rust'
    needs: cancel

  # Run the serialization tests
  serialization-tests:
    uses: lf-lang/lingua-franca/.github/workflows/serialization-tests.yml@master
    needs: cancel
