name: Rust-based tests

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - 'nightly'
    paths:
    - 'org.lflang/src/org/lflang/generator/rust/**'
    - 'org.lflang/src/lib/rs/**'

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

jobs:
  # Cancel previous workflow runs.
  cancel:
    uses: ./.github/workflows/cancel.yml

  rs-tests:
    uses: ./.github/workflows/only-rs.yml
    needs: cancel

  # Run the serialization tests
  serialization-tests:
    uses: ./.github/workflows/serialization-tests.yml
    needs: cancel
