# Non-target-specific tests to run on PRs that are ready for review.
name: Catch-all

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

concurrency:
  group: all-non-target-specific-${{ github.ref }}-${{ github.event_path }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:

  # Run the non-target-specific tests.
  non-target-specific:
    if: ${{ !github.event.pull_request.draft  }}
    uses: ./.github/workflows/non-target-specific.yml
    with:
      all: true

  # Run the non-target-specific tests.
  non-target-specific-extended:
    if: ${{ !github.event.pull_request.draft  }}
    uses: ./.github/workflows/non-target-specific-extended.yml
    with:
      all: true
