name: Non-target-specific tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - 'org.lflang/src/org/lflang/generator/c/**'
    - 'org.lflang/src/org/lflang/generator/cpp/**'
    - 'org.lflang/src/org/lflang/generator/python/**'
    - 'org.lflang/src/org/lflang/generator/rust/**'
    - 'org.lflang/src/org/lflang/generator/ts/**'
    - 'org.lflang/src/lib/c/**'
    - 'org.lflang/src/lib/platform/**'
    - 'org.lflang/src/lib/cpp/**'
    - 'org.lflang/src/lib/py/**'
    - 'org.lflang/src/lib/rs/**'
    - 'org.lflang/src/lib/ts/**'

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

jobs:
  # Cancel previous workflow runs.
  cancel:
    uses: lf-lang/lingua-franca/.github/workflows/cancel.yml@master

  # Test the Gradle build.
  build:
    uses: lf-lang/lingua-franca/.github/workflows/build.yml@master
    needs: cancel

  # Build the tools used for processing execution traces
  build-tracing-tools:
    uses: lf-lang/lingua-franca/.github/workflows/build-trace-tools.yml@master
    needs: cancel

  # Run the unit tests.
  unit-tests:
    uses: lf-lang/lingua-franca/.github/workflows/unit-tests.yml@master
    needs: cancel

  # Run tests for the standalone compiler.
  cli-tests:
    uses: lf-lang/lingua-franca/.github/workflows/cli-tests.yml@master
    needs: cancel

  # Run language server tests.
  lsp-tests:
    uses: lf-lang/lingua-franca/.github/workflows/lsp-tests.yml@master
    needs: cancel

  # Run the serialization tests
  serialization-tests:
    uses: lf-lang/lingua-franca/.github/workflows/serialization-tests.yml@master
    needs: cancel
