# Target-specific tests to run on PRs that are ready for review.
name: CI (main)

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_path }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:

  # Run the C tests.
  c:
    if: ${{ !github.event.pull_request.draft  }}
    uses: ./.github/workflows/only-c.yml
    with:
      all: true

  # Run the C++ tests.
  cpp:
    if: ${{ !github.event.pull_request.draft  }}
    uses: ./.github/workflows/only-cpp.yml
    with:
      all: true

  # Run the Python tests.
  py:
    if: ${{ !github.event.pull_request.draft  }}
    uses: ./.github/workflows/only-py.yml
    with:
      all: true

  # Run the Rust tests.
  rs:
    if: ${{ !github.event.pull_request.draft  }}
    uses: ./.github/workflows/only-rs.yml
    with:
      all: true

  # Run the TypeScript tests.
  ts:
    if: ${{ !github.event.pull_request.draft  }}
    uses: ./.github/workflows/only-ts.yml
    with:
      all: true
