name: Build the tools for processing execution traces

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      # - name: Prepare build environment
      #   uses: ./.github/actions/prepare-build-env
      - name: Run make
        working-directory: ./util/tracing
        run: make
        shell: bash
