name: Build toolchain

on:
  workflow_call:
    inputs:
      nightly:
        required: false
        type: boolean
        default: false
    secrets:
      envPAT:
        required: false
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
      - name: Build and package lf cli tools (nightly build)
        run: ./gradlew build -Pnightly
        shell: bash
        if: ${{ inputs.nightly == true }}
      - name: Build and package lf cli tools (regular build)
        run: ./gradlew build
        shell: bash
        if: ${{ inputs.nightly != true }}
      - name: Test lfc bash scripts (Linux or macOS only)
        run: |
          .github/scripts/test-lfc.sh
        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      - name: Test lff bash scripts (Linux or macOS only)
        run: |
          .github/scripts/test-lff.sh
        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      - name: Test PowerShell lfc script (Windows only)
        run: |
          ./gradlew buildAll
          bin/lfc.ps1 --help
        if: ${{ runner.os == 'Windows' }}
      - name: Test PowerShell lff script (Windows only)
        run: |
          ./gradlew buildAll
          bin/lfc.ps1 --help
        if: ${{ runner.os == 'Windows' }}
      - name: Deploy nightly release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.envPAT }}"
          automatic_release_tag: 'nightly'
          prerelease: true
          title: "Lingua Franca Nightly"
          files: |
            build/distributions/*
        if: ${{ inputs.nightly == true }}
      - name: Collect code coverage
        run: ./gradlew jacocoTestReport
        if: ${{ runner.os == 'Linux' }}
      - name: Report to CodeCov
        uses: codecov/codecov-action@v3.1.1
        with:
          files: org.lflang/core/build/reports/xml/jacoco,org.lflang/cli/lfc/build/reports/xml/jacoco,org.lflang/cli/lff/build/reports/xml/jacoco
          fail_ci_if_error: false
          verbose: true
