name: C Zephyr tests

on:
  workflow_call:
    inputs:
      compiler-ref:
        required: false
        type: string
      runtime-ref:
        required: false
        type: string
      use-cpp:
        required: false
        type: boolean
        default: false
      scheduler:
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/zephyr-build:latest
      options: -u root --entrypoint /bin/sh 
    steps:
      - name: Install Java 17, Maven and set JAVA_HOME
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          sudo apt-get install -y maven
          echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" | sudo tee -a /etc/environment
          source /etc/environment
    steps:
      - name: Initialize zephyr
        run: |
          ZEPHYR_INSTALL=/workdir/zephyrproject
          west init $ZEPHYR_INSTALL --mr v3.2.0
          cd $ZEPHYR_INSTALL 
          west update
          export ZEPHYR_BASE $ZEPHYR_INSTALL/zephyr
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          repository: lf-lang/lingua-franca
          submodules: true
          ref: ${{ inputs.compiler-ref }}
          fetch-depth: 0
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
      - name: Check out specific ref of reactor-c
        uses: actions/checkout@v3
        with:
          repository: lf-lang/reactor-c
          path: org.lflang/src/lib/c/reactor-c
          ref: ${{ inputs.runtime-ref }}
        if: ${{ inputs.runtime-ref }}
      - name: Perform Zephyr tests for C target with default scheduler
        run: |
          ./gradlew test --tests org.lflang.tests.runtime.CZephyrTests.*
