name: C Zephyr tests

on:
  workflow_call:
    inputs:
      compiler-ref:
        required: false
        type: string
      runtime-ref:
        required: false
        type: string
      use-cpp:
        required: false
        type: boolean
        default: false
      scheduler:
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      #FIXME: The ZEPHYR_VERSION and SDK_VERSION should not be hard-coded here.
      # But I dont know where... 
      - name: Install zephyr and west
        run : |
          sudo apt update && sudo apt upgrade -y
          wget https://apt.kitware.com/kitware-archive.sh
          sudo bash kitware-archive.sh
          sudo apt install --no-install-recommends git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
          sudo apt install python3-venv
          python3 -m venv ~/zephyrproject/.venv
          source ~/zephyrproject/.venv/bin/activate
          pip install west
          ZEPHYR_VERSION=v3.2.0
          west init --mr ${ZEPHYR_VERSION} ~/zephyrproject
          cd ~/zephyrproject
          west update
          west zephyr-export
          pip install -r ~/zephyrproject/zephyr/scripts/requirements.txt

          SDK_VERSION=0.15.2
          cd ~
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${SDK_VERSION}/zephyr-sdk-${SDK_VERSION}?linux-x86_64.tar.gz
          wget -O -
          https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${SDK_VERSION}/sha256.sum
          | shasum --check --ignore-missing

          tar xvf zephyr-sdk-${SDK_VERSION}_linux-x86_64.tar.gz /opt
          cd /opt/zephyr-sdk-${SDK_VERSION}
          ./setup.sh

          sudo cp ~/zephyr-sdk-${SDK_VERSION}/sysroots/x86_64-pokysdk-linux/usr/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d
          sudo udevadm control --reload

      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          repository: lf-lang/lingua-franca
          submodules: true
          ref: ${{ inputs.compiler-ref }}
          fetch-depth: 0
      - name: Install java and others
        run : |
          apt update
          JAVA_VERSION=17.0.5.
          wget https://download.oracle.com/java/17/archive/jdk-${JAVA_VERSION}_linux-x64_bin.tar.gz
          tar xvzf jdk-${JAVA_VERSION}_linux-x64_bin.tar.gz -C /opt
          export JAVA_HOME=/opt/jdk-${JAVA_VERSION}
          export PATH=$PATH:$JAVA_HOME/bin
          apt install maven -y
          GRADLE_VERSION=6.5.1
          wget
          https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip -P
          /tmp
          sudo unzip -d /opt/gradle /tmp/gradle-${VERSION}-bin.zip
          sudo ln -s /opt/gradle/gradle-${VERSION} /opt/gradle/latest
          export GRADLE_HOME=/opt/gradle/latest
          export PATH=${GRADLE_HOME}/bin:${PATH}

      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
      - name: Check out specific ref of reactor-c
        uses: actions/checkout@v3
        with:
          repository: lf-lang/reactor-c
          path: org.lflang/src/lib/c/reactor-c
          ref: ${{ inputs.runtime-ref }}
        if: ${{ inputs.runtime-ref }}
      - name: Perform Zephyr tests for C target with default scheduler
        run: |
          ./gradlew test --tests org.lflang.tests.runtime.CZephyrTests.*
