name: Non-target-specific tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      all:
        type: boolean
  pull_request:
    branches-ignore:
    - 'nightly'

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

jobs:
  # Run the unit tests.
  unit-tests:
    if: ${{ inputs.all || github.event.pull_request.draft }}
    uses: ./.github/workflows/unit-tests.yml
    with:
      all-platforms: ${{ !github.event.pull_request.draft  }}

  # Run the serialization tests
  serialization-tests:
    if: ${{ inputs.all || github.event.pull_request.draft }}
    uses: ./.github/workflows/serialization-tests.yml
