name: Additional non-target-specific tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      all:
        type: boolean
  pull_request:
    paths-ignore:
    - 'org.lflang/src/org/lflang/generator/c/**'
    - 'org.lflang/src/org/lflang/generator/cpp/**'
    - 'org.lflang/src/org/lflang/generator/python/**'
    - 'org.lflang/src/org/lflang/generator/rust/**'
    - 'org.lflang/src/org/lflang/generator/ts/**'
    - 'org.lflang/src/lib/c/**'
    - 'org.lflang/src/lib/platform/**'
    - 'org.lflang/src/lib/cpp/**'
    - 'org.lflang/src/lib/py/**'
    - 'org.lflang/src/lib/rs/**'
    - 'org.lflang/src/lib/ts/**'

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

concurrency:
  group: only-non-target-specific-extended-${{ github.ref }}-${{ github.event_path }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:

  # Test the Gradle build.
  build:
    if: ${{ inputs.all || github.event.pull_request.draft }}
    uses: ./.github/workflows/build.yml

  # Build the tools used for processing execution traces
  build-tracing-tools:
    if: ${{ inputs.all || github.event.pull_request.draft }}
    uses: ./.github/workflows/build-trace-tools.yml
    with:
      all-platforms: ${{ !github.event.pull_request.draft  }}

  check-format:
    if: ${{ inputs.all || github.event.pull_request.draft }}
    uses: ./.github/workflows/check-format.yml

  # Run tests for the standalone compiler.
  cli-tests:
    if: ${{ inputs.all || github.event.pull_request.draft }}
    uses: ./.github/workflows/cli-tests.yml
    with:
      all-platforms: ${{ !github.event.pull_request.draft  }}

  # Run language server tests.
  lsp-tests:
    if: ${{ inputs.all || github.event.pull_request.draft }}
    uses: ./.github/workflows/lsp-tests.yml
    with:
      all-platforms: ${{ !github.event.pull_request.draft  }}
