name: TypeScript tests

on:
  workflow_call:
    inputs:
      all-platforms:
        required: false
        default: true
        type: boolean

jobs:
  regular-tests:
    strategy:
      matrix:
        platform: ${{ (inputs.all-platforms && fromJSON('["ubuntu-latest", "macos-latest", "windows-latest"]')) || fromJSON('["ubuntu-latest"]') }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install coreutils (macOS)
        run: |
          brew install coreutils
        if: ${{ runner.os == 'macOS' }}
      - name: Install RTI
        uses: ./.github/actions/install-rti
        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      - name: Perform TypeScript tests
        run: |
          ./gradlew targetTest -Ptarget=TypeScript -Druntime="git://github.com/lf-lang/reactor-ts.git#master"
      - name: Report to CodeCov
        uses: Wandalen/wretry.action@1.3.0
        with:
          attempt_limit: 3
          attempt_delay: 2000
          action: codecov/codecov-action@v3.1.4
          with: |
            files: core/build/reports/jacoco/integrationTestCodeCoverageReport/integrationTestCodeCoverageReport.xml
            fail_ci_if_error: true
            verbose: true
        if: ${{ runner.os == 'Linux' && inputs.all-platforms }}
